// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telefonia.Model.Context;

namespace Telefonia.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20200207020531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Telefonia.Model.DDD", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CodigoDDD");

                    b.HasKey("Id");

                    b.ToTable("DDD");
                });

            modelBuilder.Entity("Telefonia.Model.Plano", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CodigoPlano");

                    b.Property<int>("FranquiaInternet");

                    b.Property<int>("Minutos");

                    b.Property<string>("Operadora");

                    b.Property<int>("Tipo");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("Telefonia.Model.PlanoDDD", b =>
                {
                    b.Property<long>("PlanoId");

                    b.Property<long>("DDDId");

                    b.Property<long?>("Id");

                    b.HasKey("PlanoId", "DDDId");

                    b.HasIndex("DDDId");

                    b.ToTable("PlanoDDDs");
                });

            modelBuilder.Entity("Telefonia.Model.PlanoDDD", b =>
                {
                    b.HasOne("Telefonia.Model.DDD", "DDD")
                        .WithMany("PlanoDDDs")
                        .HasForeignKey("DDDId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Telefonia.Model.Plano", "Plano")
                        .WithMany("PlanoDDDs")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
