// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telefonia.Model.Context;

namespace Telefonia.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Telefonia.Model.DDD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CodigoDDD")
                        .HasColumnName("codigo_ddd");

                    b.HasKey("Id");

                    b.ToTable("DDD");
                });

            modelBuilder.Entity("Telefonia.Model.Operadora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Operadoras");
                });

            modelBuilder.Entity("Telefonia.Model.Plano", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CodigoPlano")
                        .HasColumnName("codigo_plano");

                    b.Property<int>("FranquiaInternet")
                        .HasColumnName("franquia_internet");

                    b.Property<int>("Minutos")
                        .HasColumnName("minutos");

                    b.Property<long>("OperadoraId")
                        .HasColumnName("operadora_id");

                    b.Property<int>("Tipo")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("OperadoraId");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("Telefonia.Model.PlanoDDD", b =>
                {
                    b.Property<long>("PlanoId")
                        .HasColumnName("plano_id");

                    b.Property<long>("DDDId")
                        .HasColumnName("ddd_id");

                    b.HasKey("PlanoId", "DDDId");

                    b.HasIndex("DDDId");

                    b.ToTable("PlanoDDDs");
                });

            modelBuilder.Entity("Telefonia.Model.Plano", b =>
                {
                    b.HasOne("Telefonia.Model.Operadora", "Operadora")
                        .WithMany("Planos")
                        .HasForeignKey("OperadoraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Telefonia.Model.PlanoDDD", b =>
                {
                    b.HasOne("Telefonia.Model.DDD", "DDD")
                        .WithMany("PlanoDDDs")
                        .HasForeignKey("DDDId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Telefonia.Model.Plano", "Plano")
                        .WithMany("PlanoDDDs")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
